import Head from 'next/head'
import Hero from '../components/Home/Hero'

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>Next commerce | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

    </div>
  )
}
